os: windows
language: shell

script:
    - choco install nodejs.install && ls -la '/c/Program Files/nodejs/' && /c/Program\ Files/nodejs/npm --version
    - git clone https://github.com/deltachat/deltachat-node.git --recursive && export PATH=/c/Program\ Files/nodejs/:$PATH && npm --version && cd deltachat-node && npm install || echo need build after installed requirements && cd ..
    - ./setup-cygwin-packages.cmd
    - ls -la /c/Users/travis
    - /c/ProgramData/chocolatey/bin/cyg-get.bat python3 python3-pip python3-devel gcc-g++ gcc-fortran libgcrypt20 libgpg-error0 libxslt python3-asn1crypto python3-cffi python3-chardet python3-cryptography python3-idna	python3-lockfile python3-lxml python3-openssl python3-ply python3-pycparser	python3-requests python3-urllib3  python3-wheel
    - ./travis-step1-bzip.cmd
    - echo test-win-build
